# Data Migration Performance Analyzer

## Initial Data Cleaning Steps
This document outlines the initial steps taken to clean the example output datasets of the Data Migration Benchmarking Tool available at __[DataMigrationBenchmarkingTool Github](https://github.com/yorku-ease/DataMigrationBenchmarkingTool/tree/main)__.

### The datasets being cleaned are as follows:
* db2.csv
* defaultmigration.csv
* framework.csv
* migrationEngine.csv
* performanceBenchmark.csv
* resourceConsumption.csv

### Steps Followed for Each Dataset:
1. Reading the CSV File: Utilizing the pandas library for file reading.
2. Fixing Headers Formatting: Ensuring uniformity in column headers.
3. Converting Scientific Notations: Changing scientific notations to floats for better readability.
4. Initial Data Analysis: Utilizing `.head()` and `.info()` methods to understand the data.
5. Checking for Duplicates and Null Values: Identifying and handling duplicate rows and null values.
6. Finding Features with Zero Values: Identifying features with only zero values.
7. Identifying Columns with Non-Zero Values: Locating columns with at least one non-zero value for each feature.
8. Replacing Zeroes with Nulls: Substituting zero values with Null values and dropping rows with all Null values.


### To do:
1. Cleaning Wrong Formats: Correcting any data formatting issues.
2. Cleaning Wrong Data: Removing erroneous data points.
3. Dropping Redundant Features: Eliminating unnecessary or duplicated columns.

In [1]:
import numpy as np
import pandas as pd

## Cleaning db2.csv dataset

In [2]:
db2df = pd.read_csv('db2.csv')
db2df['Experiment startTime'] = db2df['Experiment startTime'].apply(lambda x: '{:.21f}'.format(x))
db2df['TotalClearTime'] = db2df['TotalClearTime'].apply(lambda x: '{:.21f}'.format(x))
db2df.head(10)

,Experiment Number,file,limit,compressionType,stream,Experiment startTime,TotalBackupTime,TotaltransferTime,TotalMigrationTime,TotalValidationTime,...,avgsizeOnLocalMachine,sumcompressionTime,maxcompressionTime,avgcompressionTime,sumdataTransferTime,maxdataTransferTime,avgdataTransferTime,sumreadingFileTime,maxreadingFileTime,avgreadingFileTime
0,1,NO,3,testdb=>testdb,ORDERS1,1710850927.916328907012939453125,0,998.491692,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,NO,3,testdb=>testdb,ORDERS1,1710850927.916328907012939453125,0,487.788698,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,NO,3,testdb=>testdb,ORDERS1,1710850927.916328907012939453125,0,1267.468591,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,NO,3,testdb=>testdb,ORDERS1,1710850927.916328907012939453125,0,354.556273,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,NO,3,testdb=>testdb,ORDERS1,1710850927.916328907012939453125,0,1090.153455,0,0,...,0,0,0,0,0,0,0,0,0,0
5,6,NO,3,testdb=>testdb,ORDERS1,1710850927.916328907012939453125,0,870.763960,0,0,...,0,0,0,0,0,0,0,0,0,0
6,7,NO,3,testdb=>testdb,ORDERS1,1710850927.916328907012939453125,0,1060.275094,0,0,...,0,0,0,0,0,0,0,0,0,0
7,8,NO,3,testdb=>testdb,ORDERS1,1710850927.916328907012939453125,0,2214.643754,0,0,...,0,0,0,0,0,0,0,0,0,0
8,9,NO,3,testdb=>testdb,ORDERS1,1710850927.916328907012939453125,0,2237.188121,0,0,...,0,0,0,0,0,0,0,0,0,0
9,10,NO,3,testdb=>testdb,ORDERS1,1710850927.916328907012939453125,0,882.854338,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
db2df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Experiment Number       90 non-null     int64
 1   file                    90 non-null     object
 2   limit                   90 non-null     int64
 3   compressionType         90 non-null     object
 4   stream                  90 non-null     object
 5   Experiment startTime    90 non-null     object
 6   TotalBackupTime         90 non-null     int64
 7   TotaltransferTime       90 non-null     float64
 8   TotalMigrationTime      90 non-null     int64
 9   TotalValidationTime     90 non-null     int64
 10  TotalClearTime          90 non-null     object
 11  sizeOnTargetMachine     90 non-null     int64
 12  sizeOnLocalMachine      90 non-null     int64
 13  compressionTime         90 non-null     int64
 14  dataTransferTime        90 non-null     int64
 15  readingFileTime         90 non-null     int64
 16  sumsizeOnTargetMachine  90 non-null     int64
 17  maxsizeOnTargetMachine  90 non-null     int64
 18  avgsizeOnTargetMachine  90 non-null     int64
 19  sumsizeOnLocalMachine   90 non-null     int64
 20  maxsizeOnLocalMachine   90 non-null     int64
 21  avgsizeOnLocalMachine   90 non-null     int64
 22  sumcompressionTime      90 non-null     int64
 23  maxcompressionTime      90 non-null     int64
 24  avgcompressionTime      90 non-null     int64
 25  sumdataTransferTime     90 non-null     int64
 26  maxdataTransferTime     90 non-null     int64
 27  avgdataTransferTime     90 non-null     int64
 28  sumreadingFileTime      90 non-null     int64
 29  maxreadingFileTime      90 non-null     int64
 30  avgreadingFileTime      90 non-null     int64
dtypes: float64(1), int64(25), object(5)
memory usage: 21.9+ KB

In [4]:
# Checking duplication over the rows
db2df.duplicated().sum()

0

In [5]:
# Checking null values
db2df.isna().sum()

Experiment Number         0
file                      0
limit                     0
compressionType           0
stream                    0
Experiment startTime      0
TotalBackupTime           0
TotaltransferTime         0
TotalMigrationTime        0
TotalValidationTime       0
TotalClearTime            0
sizeOnTargetMachine       0
sizeOnLocalMachine        0
compressionTime           0
dataTransferTime          0
readingFileTime           0
sumsizeOnTargetMachine    0
maxsizeOnTargetMachine    0
avgsizeOnTargetMachine    0
sumsizeOnLocalMachine     0
maxsizeOnLocalMachine     0
avgsizeOnLocalMachine     0
sumcompressionTime        0
maxcompressionTime        0
avgcompressionTime        0
sumdataTransferTime       0
maxdataTransferTime       0
avgdataTransferTime       0
sumreadingFileTime        0
maxreadingFileTime        0
avgreadingFileTime        0
dtype: int64

In [6]:
# Find columns where all values are the same
zero_columns = [col for col in db2df.columns if (db2df[col] == 0).all()] 
print(zero_columns)
print("Columns with all zero values:", len(zero_columns))

# Finding columns with values
valued_columns = [col for col in db2df.columns if (db2df[col] != 0).all()] 
print(valued_columns)
print("Columns with distinct values:", len(valued_columns))

['TotalBackupTime', 'TotalMigrationTime', 'TotalValidationTime', 'sizeOnTargetMachine', 'sizeOnLocalMachine', 'compressionTime', 'dataTransferTime', 'readingFileTime', 'sumsizeOnTargetMachine', 'maxsizeOnTargetMachine', 'avgsizeOnTargetMachine', 'sumsizeOnLocalMachine', 'maxsizeOnLocalMachine', 'avgsizeOnLocalMachine', 'sumcompressionTime', 'maxcompressionTime', 'avgcompressionTime', 'sumdataTransferTime', 'maxdataTransferTime', 'avgdataTransferTime', 'sumreadingFileTime', 'maxreadingFileTime', 'avgreadingFileTime']
Columns with all zero values: 23
['Experiment Number', 'file', 'limit', 'compressionType', 'stream', 'Experiment startTime', 'TotaltransferTime', 'TotalClearTime']
Columns with distinct values: 8

In [7]:
# Replacing the zero columns to null and drop them
db2df = db2df.replace(0, np.nan).dropna(axis=1, how='all')

In [8]:
db2df.head(10)

,Experiment Number,file,limit,compressionType,stream,Experiment startTime,TotaltransferTime,TotalClearTime
0,1,NO,3,testdb=>testdb,ORDERS1,1710850927.916328907012939453125,998.491692,0.000000476837158203125
1,2,NO,3,testdb=>testdb,ORDERS1,1710850927.916328907012939453125,487.788698,0.000000000000000000000
2,3,NO,3,testdb=>testdb,ORDERS1,1710850927.916328907012939453125,1267.468591,0.000000476837158203125
3,4,NO,3,testdb=>testdb,ORDERS1,1710850927.916328907012939453125,354.556273,0.000000000000000000000
4,5,NO,3,testdb=>testdb,ORDERS1,1710850927.916328907012939453125,1090.153455,0.000000000000000000000
5,6,NO,3,testdb=>testdb,ORDERS1,1710850927.916328907012939453125,870.763960,0.000000238418579101562
6,7,NO,3,testdb=>testdb,ORDERS1,1710850927.916328907012939453125,1060.275094,0.000000238418579101562
7,8,NO,3,testdb=>testdb,ORDERS1,1710850927.916328907012939453125,2214.643754,0.000000238418579101562
8,9,NO,3,testdb=>testdb,ORDERS1,1710850927.916328907012939453125,2237.188121,0.000000000000000000000
9,10,NO,3,testdb=>testdb,ORDERS1,1710850927.916328907012939453125,882.854338,0.000000000000000000000

## Cleaning defaultMigration.csv dataset

In [9]:
defaultMigrationdf = pd.read_csv('defaultmigration.csv', index_col=False)
defaultMigrationdf['Experiment startTime'] = defaultMigrationdf['Experiment startTime'].apply(lambda x: '{:.21f}'.format(x))
defaultMigrationdf['TotalClearTime'] = defaultMigrationdf['TotalClearTime'].apply(lambda x: '{:.21f}'.format(x))
defaultMigrationdf['avgsizeOnLocalMachine'] = defaultMigrationdf['avgsizeOnLocalMachine'].apply(lambda x: '{:.23f}'.format(x))
defaultMigrationdf['sumsizeOnTargetMachine'] = defaultMigrationdf['sumsizeOnTargetMachine'].apply(lambda x: '{:.0f}'.format(x))
defaultMigrationdf['sumcompressionTime'] = defaultMigrationdf['sumcompressionTime'].apply(lambda x: '{:.0f}'.format(x))
defaultMigrationdf['maxcompressionTime'] = defaultMigrationdf['maxcompressionTime'].apply(lambda x: '{:.20f}'.format(x))
defaultMigrationdf['sumcompressionTime'] = defaultMigrationdf['sumcompressionTime'].astype(float)
defaultMigrationdf['sumcompressionTime'] = defaultMigrationdf['sumcompressionTime'].apply(lambda x: '{:.20f}'.format(x))
defaultMigrationdf['avgcompressionTime'] = defaultMigrationdf['avgcompressionTime'].apply(lambda x: '{:.20f}'.format(x))


defaultMigrationdf.head(10)

,Experiment Number,file,limit,compressionType,stream,Experiment startTime,TotalBackupTime,TotaltransferTime,TotalMigrationTime,TotalValidationTime,...,avgsizeOnLocalMachine,sumcompressionTime,maxcompressionTime,avgcompressionTime,sumdataTransferTime,maxdataTransferTime,avgdataTransferTime,sumreadingFileTime,maxreadingFileTime,avgreadingFileTime
0,1,exported_ORDERS1.sql,104857600,NaN,3,1711135902.153998851776123046875,0,55.835815,0,0,...,638084164.66666662693023681640625,0.00000000000000000000,0.00000000000000000000,0.00000000000000000000,57.440493,31.038122,19.146831,0.227983,0.082422,0.075994
1,2,exported_ORDERS1.sql,104857600,NaN,3,1711135902.153998851776123046875,0,38.009834,0,0,...,638084164.66666662693023681640625,0.00000000000000000000,0.00000000000000000000,0.00000000000000000000,59.333389,20.132411,19.777796,0.227265,0.082973,0.075755
2,3,exported_ORDERS1.sql,104857600,NaN,3,1711135902.153998851776123046875,0,46.477951,0,0,...,638084164.66666662693023681640625,0.00000000000000000000,0.00000000000000000000,0.00000000000000000000,58.883515,25.076225,19.627838,0.227940,0.079758,0.075980
3,4,exported_ORDERS1.sql,104857600,NaN,3,1711135902.153998851776123046875,0,34.609501,0,0,...,638084164.66666662693023681640625,0.00000000000000000000,0.00000000000000000000,0.00000000000000000000,59.544106,20.857522,19.848035,0.227580,0.087153,0.075860
4,5,exported_ORDERS1.sql,104857600,NaN,3,1711135902.153998851776123046875,0,34.008436,0,0,...,638084164.66666662693023681640625,0.00000000000000000000,0.00000000000000000000,0.00000000000000000000,55.756205,18.982275,18.585402,0.219769,0.076123,0.073256
5,6,exported_ORDERS1.sql,104857600,NaN,3,1711135902.153998851776123046875,0,32.255008,0,0,...,638084164.66666662693023681640625,0.00000000000000000000,0.00000000000000000000,0.00000000000000000000,57.006313,19.146601,19.002104,0.219953,0.079196,0.073318
6,7,exported_ORDERS1.sql,104857600,NaN,3,1711135902.153998851776123046875,0,67.029736,0,0,...,638084164.66666662693023681640625,0.00000000000000000000,0.00000000000000000000,0.00000000000000000000,85.895920,45.875272,28.631973,0.218073,0.076167,0.072691
7,8,exported_ORDERS1.sql,104857600,NaN,3,1711135902.153998851776123046875,0,65.671008,0,0,...,638084164.66666662693023681640625,0.00000000000000000000,0.00000000000000000000,0.00000000000000000000,75.784123,47.519397,25.261374,0.213709,0.073979,0.071236
8,9,exported_ORDERS1.sql,104857600,NaN,3,1711135902.153998851776123046875,0,37.935396,0,0,...,638084164.66666662693023681640625,0.00000000000000000000,0.00000000000000000000,0.00000000000000000000,54.706430,19.785727,18.235477,0.209554,0.073608,0.069851
9,10,exported_ORDERS1.sql,104857600,NaN,3,1711135902.153998851776123046875,0,33.649433,0,0,...,638084164.66666662693023681640625,0.00000000000000000000,0.00000000000000000000,0.00000000000000000000,58.650752,20.202140,19.550251,0.263762,0.102557,0.087921

In [10]:
column_name_before_clean = defaultMigrationdf.columns
print(defaultMigrationdf.columns)

Index(['Experiment Number', 'file', 'limit', 'compressionType', 'stream',
       'Experiment startTime', 'TotalBackupTime', 'TotaltransferTime',
       'TotalMigrationTime', 'TotalValidationTime', 'TotalClearTime',
       'sizeOnTargetMachine', 'sizeOnLocalMachine', 'compressionTime',
       'dataTransferTime', 'readingFileTime', 'sumsizeOnTargetMachine',
       'maxsizeOnTargetMachine', 'avgsizeOnTargetMachine',
       'sumsizeOnLocalMachine', 'maxsizeOnLocalMachine',
       'avgsizeOnLocalMachine', 'sumcompressionTime', 'maxcompressionTime',
       'avgcompressionTime', 'sumdataTransferTime', 'maxdataTransferTime',
       'avgdataTransferTime', 'sumreadingFileTime', 'maxreadingFileTime',
       'avgreadingFileTime'],
      dtype='object')

In [11]:
defaultMigrationdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Experiment Number       90 non-null     int64
 1   file                    90 non-null     object
 2   limit                   90 non-null     int64
 3   compressionType         60 non-null     object
 4   stream                  90 non-null     int64
 5   Experiment startTime    90 non-null     object
 6   TotalBackupTime         90 non-null     int64
 7   TotaltransferTime       90 non-null     float64
 8   TotalMigrationTime      90 non-null     int64
 9   TotalValidationTime     90 non-null     int64
 10  TotalClearTime          90 non-null     object
 11  sizeOnTargetMachine     90 non-null     int64
 12  sizeOnLocalMachine      90 non-null     int64
 13  compressionTime         90 non-null     int64
 14  dataTransferTime        90 non-null     int64
 15  readingFileTime         90 non-null     int64
 16  sumsizeOnTargetMachine  90 non-null     object
 17  maxsizeOnTargetMachine  90 non-null     float64
 18  avgsizeOnTargetMachine  90 non-null     float64
 19  sumsizeOnLocalMachine   90 non-null     float64
 20  maxsizeOnLocalMachine   90 non-null     float64
 21  avgsizeOnLocalMachine   90 non-null     object
 22  sumcompressionTime      90 non-null     object
 23  maxcompressionTime      90 non-null     object
 24  avgcompressionTime      90 non-null     object
 25  sumdataTransferTime     90 non-null     float64
 26  maxdataTransferTime     90 non-null     float64
 27  avgdataTransferTime     90 non-null     float64
 28  sumreadingFileTime      90 non-null     float64
 29  maxreadingFileTime      90 non-null     float64
 30  avgreadingFileTime      90 non-null     float64
dtypes: float64(11), int64(11), object(9)
memory usage: 21.9+ KB

In [12]:
# Checking duplication over the rows
defaultMigrationdf.duplicated().sum()

0

In [13]:
# Checking null values
defaultMigrationdf.isna().sum()

Experiment Number          0
file                       0
limit                      0
compressionType           30
stream                     0
Experiment startTime       0
TotalBackupTime            0
TotaltransferTime          0
TotalMigrationTime         0
TotalValidationTime        0
TotalClearTime             0
sizeOnTargetMachine        0
sizeOnLocalMachine         0
compressionTime            0
dataTransferTime           0
readingFileTime            0
sumsizeOnTargetMachine     0
maxsizeOnTargetMachine     0
avgsizeOnTargetMachine     0
sumsizeOnLocalMachine      0
maxsizeOnLocalMachine      0
avgsizeOnLocalMachine      0
sumcompressionTime         0
maxcompressionTime         0
avgcompressionTime         0
sumdataTransferTime        0
maxdataTransferTime        0
avgdataTransferTime        0
sumreadingFileTime         0
maxreadingFileTime         0
avgreadingFileTime         0
dtype: int64

In [14]:
# Finding columns where all values are the same
zero_columns = [col for col in defaultMigrationdf.columns if (defaultMigrationdf[col] == 0.0).all()] 
print(zero_columns)
print("Columns with all zero values:", len(zero_columns))

# Finding columns with values
valued_columns = [col for col in defaultMigrationdf.columns if (defaultMigrationdf[col] != 0).all()] 
print(valued_columns)
print("Columns with distinct values:", len(valued_columns))

['TotalBackupTime', 'TotalMigrationTime', 'TotalValidationTime', 'sizeOnTargetMachine', 'sizeOnLocalMachine', 'compressionTime', 'dataTransferTime', 'readingFileTime']
Columns with all zero values: 8
['Experiment Number', 'file', 'limit', 'compressionType', 'stream', 'Experiment startTime', 'TotaltransferTime', 'TotalClearTime', 'sumsizeOnTargetMachine', 'maxsizeOnTargetMachine', 'avgsizeOnTargetMachine', 'sumsizeOnLocalMachine', 'maxsizeOnLocalMachine', 'avgsizeOnLocalMachine', 'sumcompressionTime', 'maxcompressionTime', 'avgcompressionTime', 'sumdataTransferTime', 'maxdataTransferTime', 'avgdataTransferTime', 'sumreadingFileTime', 'maxreadingFileTime', 'avgreadingFileTime']
Columns with distinct values: 23

In [15]:
# Checking the missing columns form the lists
# column_name_after_clean = defaultMigrationdf.columns
# original_col_set = set(column_name_before_clean)
# after_col_set = set(valued_columns)
# zero_col_set = set(zero_columns)

# missing_cols = original_col_set - after_col_set
# missing_cols = missing_cols - zero_col_set

# print(missing_cols)

In [16]:
# Replacing the zero columns to null and drop them
defaultMigrationdf = defaultMigrationdf.replace(0, np.nan).dropna(axis=1, how='all')

In [17]:
defaultMigrationdf.head()

,Experiment Number,file,limit,compressionType,stream,Experiment startTime,TotaltransferTime,TotalClearTime,sumsizeOnTargetMachine,maxsizeOnTargetMachine,...,avgsizeOnLocalMachine,sumcompressionTime,maxcompressionTime,avgcompressionTime,sumdataTransferTime,maxdataTransferTime,avgdataTransferTime,sumreadingFileTime,maxreadingFileTime,avgreadingFileTime
0,1,exported_ORDERS1.sql,104857600,NaN,3,1711135902.153998851776123046875,55.835815,0.000000953674316406250,1914252494,638084165.0,...,638084164.66666662693023681640625,0.00000000000000000000,0.00000000000000000000,0.00000000000000000000,57.440493,31.038122,19.146831,0.227983,0.082422,0.075994
1,2,exported_ORDERS1.sql,104857600,NaN,3,1711135902.153998851776123046875,38.009834,0.000000000000000000000,1914252494,638084165.0,...,638084164.66666662693023681640625,0.00000000000000000000,0.00000000000000000000,0.00000000000000000000,59.333389,20.132411,19.777796,0.227265,0.082973,0.075755
2,3,exported_ORDERS1.sql,104857600,NaN,3,1711135902.153998851776123046875,46.477951,0.000000238418579101562,1914252494,638084165.0,...,638084164.66666662693023681640625,0.00000000000000000000,0.00000000000000000000,0.00000000000000000000,58.883515,25.076225,19.627838,0.227940,0.079758,0.075980
3,4,exported_ORDERS1.sql,104857600,NaN,3,1711135902.153998851776123046875,34.609501,0.000000000000000000000,1914252494,638084165.0,...,638084164.66666662693023681640625,0.00000000000000000000,0.00000000000000000000,0.00000000000000000000,59.544106,20.857522,19.848035,0.227580,0.087153,0.075860
4,5,exported_ORDERS1.sql,104857600,NaN,3,1711135902.153998851776123046875,34.008436,0.000000238418579101562,1914252494,638084165.0,...,638084164.66666662693023681640625,0.00000000000000000000,0.00000000000000000000,0.00000000000000000000,55.756205,18.982275,18.585402,0.219769,0.076123,0.073256

## Cleaning framework.csv dataset

In [18]:
frameworkdf = pd.read_csv('framework.csv', index_col=False)
frameworkdf['Timestamp'] = frameworkdf['Timestamp'].apply(lambda x: '{:.21f}'.format(x))
frameworkdf['Experiment startTime'] = frameworkdf['Experiment startTime'].apply(lambda x: '{:.22f}'.format(x))
frameworkdf.head(10)

,Experiment Number,file,limit,compressionType,stream,Experiment startTime,type,Experiment,Timestamp
0,1,ubuntu.iso,1048576,NaN,1,1705721671.4707601070404052734375,info,started,1705721671.470808506011962890625
1,1,ubuntu.iso,1048576,NaN,1,1705721671.4707601070404052734375,info,completed,1705721802.115096092224121093750
2,1,ubuntu.iso,1048576,NaN,3,1705721802.1152970790863037109375,info,started,1705721802.115315675735473632812
3,1,ubuntu.iso,1048576,NaN,3,1705721802.1152970790863037109375,info,completed,1705721945.557554960250854492188
4,1,ubuntu.iso,1048576,gzip,1,1705721945.5577855110168457031250,info,started,1705721945.557803153991699218750
5,1,ubuntu.iso,1048576,gzip,1,1705721945.5577855110168457031250,info,completed,1705722232.060883045196533203125
6,1,ubuntu.iso,1048576,gzip,3,1705722232.0609145164489746093750,info,started,1705722232.060932159423828125000
7,1,ubuntu.iso,1048576,gzip,3,1705722232.0609145164489746093750,info,completed,1705722379.665190458297729492188

In [19]:
frameworkdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Experiment Number     8 non-null      int64
 1   file                  8 non-null      object
 2   limit                 8 non-null      int64
 3   compressionType       4 non-null      object
 4   stream                8 non-null      int64
 5   Experiment startTime  8 non-null      object
 6   type                  8 non-null      object
 7   Experiment            8 non-null      object
 8   Timestamp             8 non-null      object
dtypes: int64(3), object(6)
memory usage: 708.0+ bytes

In [20]:
# Checking duplication over the rows
frameworkdf.duplicated().sum()

0

In [21]:
# Checking null values
frameworkdf.isna().sum()

Experiment Number       0
file                    0
limit                   0
compressionType         4
stream                  0
Experiment startTime    0
type                    0
Experiment              0
Timestamp               0
dtype: int64

In [22]:
# Finding columns where all values are the same
zero_columns = [col for col in frameworkdf.columns if (frameworkdf[col] == 0.0).all()] 
print(zero_columns)
print("Columns with all zero values:", len(zero_columns))

# Finding columns with values
valued_columns = [col for col in frameworkdf.columns if (frameworkdf[col] != 0).all()] 
print(valued_columns)
print("Columns with distinct values:", len(valued_columns))

[]
Columns with all zero values: 0
['Experiment Number', 'file', 'limit', 'compressionType', 'stream', 'Experiment startTime', 'type', 'Experiment', 'Timestamp']
Columns with distinct values: 9

## Cleaning migrationEngine.csv dataset

### Issues:
* The dataset has 10 columns, but each row has 11 values (the last column doesn't have a header)

In [23]:
migrationEnginedf = pd.read_csv('migrationEngine.csv')
migrationEnginedf['Timestamp'] = migrationEnginedf['Timestamp'].apply(lambda x: '{:.22f}'.format(x))

# 'Experiment startTime' needs to be converted
# migrationEnginedf['Experiment startTime'] = migrationEnginedf['Experiment startTime'].astype(float)
# migrationEnginedf['Experiment startTime'] = migrationEnginedf['Experiment startTime'].apply(lambda x: '{:.22f}'.format(x))

migrationEnginedf.head(10)

,Experiment Number,file,limit,compressionType,streams,Experiment startTime,type,operation,Timestamp,stream
1,ubuntu.iso,1048576,NaN,1,1.705722e+09,info,migration,started,1705721672.2703685760498046875000,NaN
1,ubuntu.iso,1048576,NaN,1,1.705722e+09,info,ReadingFile,started,1705721672.5339295864105224609375,NaN
1,ubuntu.iso,1048576,NaN,1,1.705722e+09,info,ReadingFile,completed,1705721672.5351002216339111328125,NaN
1,ubuntu.iso,1048576,NaN,1,1.705722e+09,info,FileChunk1Transfer,started,1705721672.5351157188415527343750,NaN
1,ubuntu.iso,1048576,NaN,1,1.705722e+09,info,FileChunk1Transfer,completed,1705721672.5881164073944091796875,NaN
1,ubuntu.iso,1048576,NaN,1,1.705722e+09,info,FileChunk2Transfer,started,1705721672.5985987186431884765625,NaN
1,ubuntu.iso,1048576,NaN,1,1.705722e+09,info,FileChunk2Transfer,completed,1705721672.6580185890197753906250,NaN
1,ubuntu.iso,1048576,NaN,1,1.705722e+09,info,FileChunk3Transfer,started,1705721672.6665275096893310546875,NaN
1,ubuntu.iso,1048576,NaN,1,1.705722e+09,info,FileChunk3Transfer,completed,1705721672.6992342472076416015625,NaN
1,ubuntu.iso,1048576,NaN,1,1.705722e+09,info,FileChunk4Transfer,started,1705721672.7011997699737548828125,NaN

In [24]:
migrationEnginedf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 57702 entries, 1 to 1
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Experiment Number     57702 non-null  object
 1   file                  57702 non-null  int64
 2   limit                 38462 non-null  object
 3   compressionType       57702 non-null  int64
 4   streams               57702 non-null  float64
 5   Experiment startTime  57702 non-null  object
 6   type                  57702 non-null  object
 7   operation             57702 non-null  object
 8   Timestamp             57702 non-null  object
 9   stream                28860 non-null  float64
dtypes: float64(2), int64(2), object(6)
memory usage: 4.8+ MB

In [25]:
# Checking duplication over the rows
migrationEnginedf.duplicated().sum()

0

In [26]:
# Checking null values
migrationEnginedf.isna().sum()

Experiment Number           0
file                        0
limit                   19240
compressionType             0
streams                     0
Experiment startTime        0
type                        0
operation                   0
Timestamp                   0
stream                  28842
dtype: int64

In [27]:
# Finding columns where all values are the same
zero_columns = [col for col in migrationEnginedf.columns if (migrationEnginedf[col] == 0.0).all()] 
print(zero_columns)
print("Columns with all zero values:", len(zero_columns))

# Finding columns with values
valued_columns = [col for col in migrationEnginedf.columns if (migrationEnginedf[col] != 0).all()] 
print(valued_columns)
print("Columns with distinct values:", len(valued_columns))

[]
Columns with all zero values: 0
['Experiment Number', 'file', 'limit', 'compressionType', 'streams', 'Experiment startTime', 'type', 'operation', 'Timestamp', 'stream']
Columns with distinct values: 10

## Cleaning performanceBenchMark.csv dataset

In [28]:
performanceBMdf = pd.read_csv('performanceBenchmark.csv')
performanceBMdf.head(10)

,|,|__1__TotalClearTime,|__1__|,|__1__|__sizeOnTargetMachine,|__1__|__sizeOnLocalMachine,|__1__|__compressionTime,|__1__|__dataTransferTime,|__1__|__readingFileTime,|__1__None__sizeOnTargetMachine,|__1__None__sizeOnLocalMachine,|__1__None__compressionTime,|__1__None__dataTransferTime,|__1__None__readingFileTime,|__1__TotaltransferTime
0,ubuntu.iso-1048576-None-1-1705721671.4707599,2.384186e-07,NaN,NaN,NaN,NaN,NaN,NaN,5.037662e+09,5.037662e+09,0.000000,83.530469,0.000888,130.644511
1,ubuntu.iso-1048576-None-3-1705721802.115297,2.384186e-07,2.0,1.679221e+09,1.679221e+09,0.000000,106.426617,0.000652,NaN,NaN,NaN,NaN,NaN,143.442467
2,NaN,NaN,3.0,1.679221e+09,1.679221e+09,0.000000,105.872388,0.000679,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,1.0,1.679221e+09,1.679221e+09,0.000000,103.001307,0.001170,NaN,NaN,NaN,NaN,NaN,NaN
4,ubuntu.iso-1048576-gzip-1-1705721945.5577855,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,5.006647e+09,5.006647e+09,193.108311,62.310376,0.001770,286.503109
5,ubuntu.iso-1048576-gzip-3-1705722232.0609145,2.384186e-07,2.0,1.677016e+09,1.677016e+09,70.746034,43.576568,0.000680,NaN,NaN,NaN,NaN,NaN,147.604295
6,NaN,NaN,3.0,1.670424e+09,1.670424e+09,72.018873,43.981150,0.000633,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,1.0,1.659212e+09,1.659212e+09,73.581397,41.752311,0.007347,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
performanceBMdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 14 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   |                                4 non-null      object
 1   |__1__TotalClearTime             4 non-null      float64
 2   |__1__|                          6 non-null      float64
 3   |__1__|__sizeOnTargetMachine     6 non-null      float64
 4   |__1__|__sizeOnLocalMachine      6 non-null      float64
 5   |__1__|__compressionTime         6 non-null      float64
 6   |__1__|__dataTransferTime        6 non-null      float64
 7   |__1__|__readingFileTime         6 non-null      float64
 8   |__1__None__sizeOnTargetMachine  2 non-null      float64
 9   |__1__None__sizeOnLocalMachine   2 non-null      float64
 10  |__1__None__compressionTime      2 non-null      float64
 11  |__1__None__dataTransferTime     2 non-null      float64
 12  |__1__None__readingFileTime      2 non-null      float64
 13  |__1__TotaltransferTime          4 non-null      float64
dtypes: float64(13), object(1)
memory usage: 1.0+ KB

Formating the header names to remove teh extra characters.

In [30]:
def clean_header(header):
    header = header.lstrip('|')  # Remove leading '|'
    header = header.replace('__1__|', '')  # Remove '__1__|'
    header = header.replace('__1__', '')  # Remove '__1__'
    header = header.replace('|', '')  # Remove remaining '|'
    header = header.replace('__', '_')  # Replace double underscores with single
    header = header.strip('_')  # Remove leading/trailing underscores
    return header.strip()  # Remove any leading/trailing whitespace

In [31]:
headers = performanceBMdf.columns

if len(headers) != performanceBMdf.shape[1]:
    print(f"Warning: Number of headers ({len(headers)}) does not match number of DataFrame columns ({performanceBMdf.shape[1]})")


# Apply the function to all headers
cleaned_headers = [clean_header(header) if header != '|' else 'file' for header in headers]

# Check and replace any empty headers
cleaned_headers = ['Unnamed' if header == '' else header for header in cleaned_headers]

# Display cleaned headers
print("Cleaned headers:")
print(cleaned_headers)
# Assuming migrationEnginedf is your DataFrame
performanceBMdf.columns = cleaned_headers
performanceBMdf.head()

Cleaned headers:
['file', 'TotalClearTime', 'Unnamed', 'sizeOnTargetMachine', 'sizeOnLocalMachine', 'compressionTime', 'dataTransferTime', 'readingFileTime', 'None_sizeOnTargetMachine', 'None_sizeOnLocalMachine', 'None_compressionTime', 'None_dataTransferTime', 'None_readingFileTime', 'TotaltransferTime']

,file,TotalClearTime,Unnamed,sizeOnTargetMachine,sizeOnLocalMachine,compressionTime,dataTransferTime,readingFileTime,None_sizeOnTargetMachine,None_sizeOnLocalMachine,None_compressionTime,None_dataTransferTime,None_readingFileTime,TotaltransferTime
0,ubuntu.iso-1048576-None-1-1705721671.4707599,2.384186e-07,NaN,NaN,NaN,NaN,NaN,NaN,5.037662e+09,5.037662e+09,0.000000,83.530469,0.000888,130.644511
1,ubuntu.iso-1048576-None-3-1705721802.115297,2.384186e-07,2.0,1.679221e+09,1.679221e+09,0.0,106.426617,0.000652,NaN,NaN,NaN,NaN,NaN,143.442467
2,NaN,NaN,3.0,1.679221e+09,1.679221e+09,0.0,105.872388,0.000679,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,1.0,1.679221e+09,1.679221e+09,0.0,103.001307,0.001170,NaN,NaN,NaN,NaN,NaN,NaN
4,ubuntu.iso-1048576-gzip-1-1705721945.5577855,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,5.006647e+09,5.006647e+09,193.108311,62.310376,0.001770,286.503109

In [32]:
performanceBMdf['TotalClearTime'] = performanceBMdf['TotalClearTime'].apply(lambda x: '{:.22f}'.format(x))
performanceBMdf['sizeOnTargetMachine'] = performanceBMdf['sizeOnTargetMachine'].apply(lambda x: '{:.1f}'.format(x))
performanceBMdf['sizeOnLocalMachine'] = performanceBMdf['sizeOnLocalMachine'].apply(lambda x: '{:.1f}'.format(x))
performanceBMdf['None_sizeOnTargetMachine'] = performanceBMdf['None_sizeOnTargetMachine'].apply(lambda x: '{:.1f}'.format(x))
performanceBMdf['None_sizeOnLocalMachine'] = performanceBMdf['None_sizeOnLocalMachine'].apply(lambda x: '{:.1f}'.format(x))

In [33]:
performanceBMdf.head()

,file,TotalClearTime,Unnamed,sizeOnTargetMachine,sizeOnLocalMachine,compressionTime,dataTransferTime,readingFileTime,None_sizeOnTargetMachine,None_sizeOnLocalMachine,None_compressionTime,None_dataTransferTime,None_readingFileTime,TotaltransferTime
0,ubuntu.iso-1048576-None-1-1705721671.4707599,0.0000002384185791015625,NaN,nan,nan,NaN,NaN,NaN,5037662208.0,5037662208.0,0.000000,83.530469,0.000888,130.644511
1,ubuntu.iso-1048576-None-3-1705721802.115297,0.0000002384185791015625,2.0,1679220736.0,1679220736.0,0.0,106.426617,0.000652,nan,nan,NaN,NaN,NaN,143.442467
2,NaN,nan,3.0,1679220736.0,1679220736.0,0.0,105.872388,0.000679,nan,nan,NaN,NaN,NaN,NaN
3,NaN,nan,1.0,1679220736.0,1679220736.0,0.0,103.001307,0.001170,nan,nan,NaN,NaN,NaN,NaN
4,ubuntu.iso-1048576-gzip-1-1705721945.5577855,0.0000000000000000000000,NaN,nan,nan,NaN,NaN,NaN,5006646669.0,5006646669.0,193.108311,62.310376,0.001770,286.503109

In [34]:
# Checking duplication over the rows
performanceBMdf.duplicated().sum()

0

In [35]:
# Checking null values
performanceBMdf.isna().sum()

file                        4
TotalClearTime              0
Unnamed                     2
sizeOnTargetMachine         0
sizeOnLocalMachine          0
compressionTime             2
dataTransferTime            2
readingFileTime             2
None_sizeOnTargetMachine    0
None_sizeOnLocalMachine     0
None_compressionTime        6
None_dataTransferTime       6
None_readingFileTime        6
TotaltransferTime           4
dtype: int64

In [36]:
# Finding columns where all values are the same
zero_columns = [col for col in performanceBMdf.columns if (performanceBMdf[col] == 0.0).all()] 
print(zero_columns)
print("Columns with all zero values:", len(zero_columns))

# Finding columns with values
valued_columns = [col for col in performanceBMdf.columns if (performanceBMdf[col] != 0).all()] 
print(valued_columns)
print("Columns with distinct values:", len(valued_columns))

[]
Columns with all zero values: 0
['file', 'TotalClearTime', 'Unnamed', 'sizeOnTargetMachine', 'sizeOnLocalMachine', 'dataTransferTime', 'readingFileTime', 'None_sizeOnTargetMachine', 'None_sizeOnLocalMachine', 'None_dataTransferTime', 'None_readingFileTime', 'TotaltransferTime']
Columns with distinct values: 12

In [37]:
# Replacing the zero columns to null and drop them
performanceBMdf = performanceBMdf.replace(0, np.nan).dropna(axis=1, how='all')

In [38]:
performanceBMdf.head()

,file,TotalClearTime,Unnamed,sizeOnTargetMachine,sizeOnLocalMachine,compressionTime,dataTransferTime,readingFileTime,None_sizeOnTargetMachine,None_sizeOnLocalMachine,None_compressionTime,None_dataTransferTime,None_readingFileTime,TotaltransferTime
0,ubuntu.iso-1048576-None-1-1705721671.4707599,0.0000002384185791015625,NaN,nan,nan,NaN,NaN,NaN,5037662208.0,5037662208.0,NaN,83.530469,0.000888,130.644511
1,ubuntu.iso-1048576-None-3-1705721802.115297,0.0000002384185791015625,2.0,1679220736.0,1679220736.0,NaN,106.426617,0.000652,nan,nan,NaN,NaN,NaN,143.442467
2,NaN,nan,3.0,1679220736.0,1679220736.0,NaN,105.872388,0.000679,nan,nan,NaN,NaN,NaN,NaN
3,NaN,nan,1.0,1679220736.0,1679220736.0,NaN,103.001307,0.001170,nan,nan,NaN,NaN,NaN,NaN
4,ubuntu.iso-1048576-gzip-1-1705721945.5577855,0.0000000000000000000000,NaN,nan,nan,NaN,NaN,NaN,5006646669.0,5006646669.0,193.108311,62.310376,0.001770,286.503109

## Cleaning resourceConsuption.csv dataset

In [39]:
resourcedf = pd.read_csv('resourceConsumption.csv')
resourcedf.head(10)

,status,data__resultType,data__result__metric____name__,data__result__metric__container_label_loggingId,data__result__metric__container_label_architecture,data__result__metric__container_label_build_date,data__result__metric__container_label_com_docker_compose_config_hash,data__result__metric__container_label_com_docker_compose_container_number,data__result__metric__container_label_com_docker_compose_depends_on,data__result__metric__container_label_com_docker_compose_image,...,data__result__metric__container_label_vcs_type,data__result__metric__container_label_vendor,data__result__metric__container_label_version,data__result__metric__id,data__result__metric__image,data__result__metric__instance,data__result__metric__job,data__result__metric__name,data__result__values__001,data__result__values__002
0,success,matrix,container_memory_rss,NaN,x86_64,2023-02-07T16:17:52,d4c55aad1dd17a629c0143b1f66234bad25a26ff4c9b23...,1.0,NaN,sha256:8a091961522e4ce06d832cd2b4f5f6809924f58...,...,git,Confluent,80ba7e33,/docker/f61da50d886eea57fa2feb0a6f4380233a4f91...,confluentinc/cp-zookeeper:7.3.2,localhost:8080,cAdvisor,zoo1,1.705722e+09,101711872
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.705722e+09,101711872
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.705722e+09,101711872
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.705722e+09,101711872
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.705722e+09,101711872
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.705722e+09,101711872
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.705722e+09,101711872
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.705722e+09,101711872
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.705722e+09,101711872
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.705722e+09,101711872

In [40]:
resourcedf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11927 entries, 0 to 11926
Data columns (total 47 columns):
 #   Column                                                                         Non-Null Count  Dtype
---  ------                                                                         --------------  -----
 0   status                                                                         1 non-null      object
 1   data__resultType                                                               1 non-null      object
 2   data__result__metric____name__                                                 156 non-null    object
 3   data__result__metric__container_label_loggingId                                4 non-null      object
 4   data__result__metric__container_label_architecture                             3 non-null      object
 5   data__result__metric__container_label_build_date                               3 non-null      object
 6   data__result__metric__container_label_com_docker_compose_config_hash           7 non-null      object
 7   data__result__metric__container_label_com_docker_compose_container_number      7 non-null      float64
 8   data__result__metric__container_label_com_docker_compose_depends_on            2 non-null      object
 9   data__result__metric__container_label_com_docker_compose_image                 7 non-null      object
 10  data__result__metric__container_label_com_docker_compose_oneoff                7 non-null      object
 11  data__result__metric__container_label_com_docker_compose_project               7 non-null      object
 12  data__result__metric__container_label_com_docker_compose_project_config_files  7 non-null      object
 13  data__result__metric__container_label_com_docker_compose_project_working_dir   7 non-null      object
 14  data__result__metric__container_label_com_docker_compose_service               7 non-null      object
 15  data__result__metric__container_label_com_docker_compose_version               7 non-null      object
 16  data__result__metric__container_label_org_opencontainers_image_ref_name        1 non-null      object
 17  data__result__metric__container_label_org_opencontainers_image_version         1 non-null      float64
 18  data__result__metric__container_label_com_redhat_component                     3 non-null      object
 19  data__result__metric__container_label_com_redhat_license_terms                 3 non-null      object
 20  data__result__metric__container_label_description                              3 non-null      object
 21  data__result__metric__container_label_distribution_scope                       3 non-null      object
 22  data__result__metric__container_label_io_buildah_version                       3 non-null      object
 23  data__result__metric__container_label_io_confluent_docker                      1 non-null      object
 24  data__result__metric__container_label_io_confluent_docker_build_number         1 non-null      float64
 25  data__result__metric__container_label_io_confluent_docker_git_id               1 non-null      object
 26  data__result__metric__container_label_io_confluent_docker_git_repo             1 non-null      object
 27  data__result__metric__container_label_io_k8s_description                       3 non-null      object
 28  data__result__metric__container_label_io_k8s_display_name                      3 non-null      object
 29  data__result__metric__container_label_io_openshift_tags                        3 non-null      object
 30  data__result__metric__container_label_maintainer                               6 non-null      object
 31  data__result__metric__container_label_name                                     3 non-null      object
 32  data__result__metric__container_label_release                                  3 non-null      object
 33  data__result__metric__container_label_restartcount                             1 non-null      float64
 34  data__result__metric__container_label_summary                                  3 non-null      object
 35  data__result__metric__container_label_url                                      3 non-null      object
 36  data__result__metric__container_label_vcs_ref                                  3 non-null      object
 37  data__result__metric__container_label_vcs_type                                 3 non-null      object
 38  data__result__metric__container_label_vendor                                   3 non-null      object
 39  data__result__metric__container_label_version                                  3 non-null      object
 40  data__result__metric__id                                                       156 non-null    object
 41  data__result__metric__image                                                    13 non-null     object
 42  data__result__metric__instance                                                 156 non-null    object
 43  data__result__metric__job                                                      156 non-null    object
 44  data__result__metric__name                                                     13 non-null     object
 45  data__result__values__001                                                      11927 non-null  float64
 46  data__result__values__002                                                      11927 non-null  int64
dtypes: float64(5), int64(1), object(41)
memory usage: 4.3+ MB

In [41]:
# Checking duplication over the rows
resourcedf.duplicated().sum()

4

In [42]:
# Checking null values
resourcedf.isna().sum()

status                                                                           11926
data__resultType                                                                 11926
data__result__metric____name__                                                   11771
data__result__metric__container_label_loggingId                                  11923
data__result__metric__container_label_architecture                               11924
data__result__metric__container_label_build_date                                 11924
data__result__metric__container_label_com_docker_compose_config_hash             11920
data__result__metric__container_label_com_docker_compose_container_number        11920
data__result__metric__container_label_com_docker_compose_depends_on              11925
data__result__metric__container_label_com_docker_compose_image                   11920
data__result__metric__container_label_com_docker_compose_oneoff                  11920
data__result__metric__container_label_com_docker_compose_project                 11920
data__result__metric__container_label_com_docker_compose_project_config_files    11920
data__result__metric__container_label_com_docker_compose_project_working_dir     11920
data__result__metric__container_label_com_docker_compose_service                 11920
data__result__metric__container_label_com_docker_compose_version                 11920
data__result__metric__container_label_org_opencontainers_image_ref_name          11926
data__result__metric__container_label_org_opencontainers_image_version           11926
data__result__metric__container_label_com_redhat_component                       11924
data__result__metric__container_label_com_redhat_license_terms                   11924
data__result__metric__container_label_description                                11924
data__result__metric__container_label_distribution_scope                         11924
data__result__metric__container_label_io_buildah_version                         11924
data__result__metric__container_label_io_confluent_docker                        11926
data__result__metric__container_label_io_confluent_docker_build_number           11926
data__result__metric__container_label_io_confluent_docker_git_id                 11926
data__result__metric__container_label_io_confluent_docker_git_repo               11926
data__result__metric__container_label_io_k8s_description                         11924
data__result__metric__container_label_io_k8s_display_name                        11924
data__result__metric__container_label_io_openshift_tags                          11924
data__result__metric__container_label_maintainer                                 11921
data__result__metric__container_label_name                                       11924
data__result__metric__container_label_release                                    11924
data__result__metric__container_label_restartcount                               11926
data__result__metric__container_label_summary                                    11924
data__result__metric__container_label_url                                        11924
data__result__metric__container_label_vcs_ref                                    11924
data__result__metric__container_label_vcs_type                                   11924
data__result__metric__container_label_vendor                                     11924
data__result__metric__container_label_version                                    11924
data__result__metric__id                                                         11771
data__result__metric__image                                                      11914
data__result__metric__instance                                                   11771
data__result__metric__job                                                        11771
data__result__metric__name                                                       11914
data__result__values__001                                                            0
data__result__values__002                                                            0
dtype: int64